file_temp_dir: "./tmp"

token_service_config:
  secret: "si@goosh-im@ge-optimizer-service"
  expration_time: 36000

authorization_service_config:
  ext_white_list:
    - "jpg"
    - "png"
    - "jpeg"

http_server_config:
  port: 8080
  workers: 2
