version: '3.8'

services:
  # redis:
  #   image: "redis:alpine"
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data


  nats: 
    image: "nats:alpine3.21"
    ports:
      - "4222:4222"
      - "8222:8222"
    command: "--http_port 8222"

  minio:
    image: quay.io/minio/minio:RELEASE.2024-12-18T13-15-44Z
    command: server --console-address ":9001" /data
    expose:
      - "9000"
      - "9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - minio-data:/data


volumes:
  redis-data:
  minio-data: