version: '3.8'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data


  nats: 
    image: "nats:alpine3.21"
    ports:
      - "4222:4222"
      - "8222:8222"
    command: "--http_port 8222"

    
  # rabbitmq:
  #   image: "rabbitmq:3-management-alpine"
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   volumes:
  #     - rabbitmq-data:/var/lib/rabbitmq
  #   environment:
  #     RABBITMQ_DEFAULT_USER: siagoosh
  #     RABBITMQ_DEFAULT_PASS: siagoosh


volumes:
  redis-data:
  rabbitmq-data:
