version: '3.8'

services:
  caddy:
    image: caddy:2.9.1-alpine
    volumes:
      - ./caddy:/etc/caddy
    ports:
      - 80:80
      - 443:443
    networks:
      - app

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app

  nats: 
    image: "nats:alpine3.21"
    command: "--http_port 8222"
    networks:
      - app

  minio:
    image: quay.io/minio/minio:RELEASE.2024-12-18T13-15-44Z
    command: server --console-address ":9001" /data
    expose:
      - "9000"
      - "9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - minio-data:/data
    networks:
      - app

volumes:
  redis-data:
  minio-data:

networks:
  app:
    driver: bridge
