file_temp_dir: "./tmp"

token_service_config:
  secret: "si@goosh-im@ge-optimizer-service"
  expiration_time: 36000
authorization_service_config:
  ext_white_list:
    - "jpg"
    - "png"
    - "jpeg"
    - "webp"

http_server_config:
  port: 5000
  workers: 2

rabbit_mq_config:
  connection_url: "amqp://siagoosh:siagoosh@localhost:5672/%2f"

nats_config:
  connection_url: "nats://localhost:4222"

image_queue_rabbitmq_config:
  queue_name: 'image_optimization_queue'
  exchange_name: "image_optimization_exchange"
  routing_key: "image_optimization"
  consumer_tag: "image_optimization_consumer_tag"

image_queue_nats_config:
  income_namespace: 'image_optimization.income'
  result_namespace: 'image_optimization.result'
  

minio_config:
  endpoint: "http://0.0.0.0:9000"
  access_key: "GeoFdEVT5jASgV4z8UXX"
  secret_key: "NUMAutLce9DxjVvl1N6os7XfHS4rPNqohTqv8cyU"
  region: "us-east-1"