type: yml

auth:
  sign_key: jwt_secret

authorization_config:
  max_successful_request_per_day: 50
  max_total_request_per_day: 70

http_server:
  port: 8088

optimizer_config:
  url: http://127.0.0.1:5000

mysql:
  port: 3308
  host: localhost
  db_name: gameapp_db
  username: gameapp
  password: gameappt0lk2o20

redis:
  port: 6380
  host: localhost
  db: 0
  password: ""
